spring:
  jpa:
    hibernate:
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.HSQLDialect
      ddl-auto: none
      naming:
        physical-naming: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    driver-class-name: org.hsqldb.jdbcDriver
    url: jdbc:hsqldb:hsql://localhost:9001/templateDB
    username: SA
    password:
  security:
    enabled: true
logging:
  level:
    org:
      hibernate:
        SQL: debug
      type:
        descriptor:
          sql: trace
server:
  port: 30030

# Este archivo se utiliza para configurar propiedades de la aplicación Spring.

# Contiene configuraciones relacionadas con la base de datos, la seguridad y el registro de eventos de la aplicación.

    # La sección spring configura la base de datos, incluyendo el dialecto de Hibernate, la URL de conexión y las credenciales.
    # La sección logging configura el nivel de registro para varias partes de la aplicación.
    # La sección server especifica el puerto en el que se ejecutará la aplicación.